trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'runner-local'

steps:
- task: Maven@3
  inputs:
    pomFile: 'pom.xml'
    goals: 'clean test'
    options: '-B'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
  displayName: 'Build and Test with Maven'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
  condition: succeededOrFailed()
  displayName: 'Publish Test Results'

- publish: $(System.DefaultWorkingDirectory)/target/surefire-reports
  artifact: selenium-reports
