trigger:
  branches:
    include:
      - main

pool:
  name: 'runner-local'

variables:
  imageName: 'selenium-tests:$(Build.BuildId)'

steps:
- checkout: self

- script: |
    echo "Building Docker Image..."
    docker build -t $(imageName) .
  displayName: 'Build Docker Image'

- script: |
    echo "Preparing local reports folder..."
    mkdir -p $(Build.SourcesDirectory)/report
  displayName: 'Create Reports Directory'

- script: |
    echo "Running Tests in Docker with volume..."
    docker run --rm \
      -v $(Build.SourcesDirectory)/report:/app/report \
      $(imageName)
  displayName: 'Run Tests and Export Reports'

- publish: $(Build.SourcesDirectory)/report
  artifact: selenium-reports
  displayName: 'Publish Selenium Reports Artifact'
