trigger:
  branches:
    include:
      - main

pool:
  name: 'runner-local'

variables:
  imageName: 'selenium-tests:$(Build.BuildId)'

steps:
- checkout: self

- script: |
    echo "Construyendo imagen Docker..."
    docker build -t $(imageName) .
  displayName: 'Build Docker Image'

- script: |
    echo "Ejecutando contenedor..."
    docker run --rm $(imageName)
  displayName: 'Run Tests in Docker'
