name: Build imagen - Docker

on:
  push:
    branches:
      - 'build'
      - 'test'
      
env:
  IMAGE_NAME: selenium-test
  
jobs:
  build-base:
    runs-on: ubuntu-24.04 
    if: "contains(github.event.head_commit.message, '[run-base]')"
    steps:
    - uses: actions/checkout@v4

    - name: Log in to registry
      run: echo "${{ secrets.PERSONAL_ACCESS_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Checkout repository
      run: docker build  --tag $IMAGE_NAME -f build/dockerfile-base .

    - name: Push image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository }}/$IMAGE_NAME
        # Change all uppercase to lowercase
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        echo IMAGE_ID=$IMAGE_ID
        docker tag $IMAGE_NAME $IMAGE_ID:base
        docker push $IMAGE_ID:base